image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
tasks:
- command: >
    bash setup.sh && bash setup_conda

vscode:
  extensions:
    - almenon.arepl@1.0.16:XGYMBgfBMAnJXoyFkfSzPA==
    - KevinRose.vsc-python-indent@1.4.0:pb+bIlsFJOAdUNBE31dQwQ==
    - ms-python.python@2019.6.24221:eSSDlQYifwrEZXcrjL0W/g==
    - ms-python.anaconda-extension-pack@1.0.1:zDfOOe7FoQk40SnrhxWS5g==
    - eamodio.gitlens@9.9.2:4mgTdhdGJaQTZHTMTMDPYg==